# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZoomLevel
                                 A QGIS plugin
 Displays the zoom level of the map in the status bar.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-01-17
        copyright            : (C) 2020 by Keith Jenkins
        email                : kgjenkins@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ZoomLevel class from file ZoomLevel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zoom_level import ZoomLevel
    return ZoomLevel(iface)
